package server_side;

//------------------------------------------------------------
//
// Implementation stub file
// 
// Target: _DbWorkStub
// Source: d:/programming/temp/erl/java/dbwork.idl
// IC vsn: 4.3
// 
// This file is automatically generated. DO NOT EDIT IT.
//
//------------------------------------------------------------


public class _DbWorkStub implements DbWork {

    // Client data
    public com.ericsson.otp.ic.Environment _env;

    // Constructors
    public _DbWorkStub(com.ericsson.otp.erlang.OtpSelf _self,
                       com.ericsson.otp.erlang.OtpPeer _peer,
                       java.lang.Object _server) throws java.lang.Exception {

      _env =
         new com.ericsson.otp.ic.Environment(_self, _peer, _server);
      _env.connect();
    }

    public _DbWorkStub(java.lang.String _selfN,
                       java.lang.String _peerN,
                       java.lang.String _cookie,
                       java.lang.Object _server) throws java.lang.Exception {

      _env =
         new com.ericsson.otp.ic.Environment(_selfN, _peerN, _cookie, _server);
      _env.connect();
    }

    public _DbWorkStub(com.ericsson.otp.erlang.OtpConnection _connection,
                       java.lang.Object _server) throws java.lang.Exception {

      _env =
         new com.ericsson.otp.ic.Environment(_connection, _server);
      _env.connect();
    }

    // Returns call reference
    public com.ericsson.otp.erlang.OtpErlangRef __getRef()
      throws java.lang.Exception {
        return _env.received_ref();
    }

    // Returns the server
    public java.lang.Object __server() {
      return _env.server();
    }

    // Closes connection
    public void __disconnect() {
      _env.disconnect();
    }

    // Reconnects client
    public void __reconnect()
      throws java.lang.Exception {
      _env.reconnect();
    }

    // Destroy server
    public void __stop()
      throws java.lang.Exception {
      _env.client_stop_server();
    }

    // Operation "DbWork::hello" implementation
    public java.lang.String hello()
      throws java.lang.Exception {

      // Calling the marshal function
      _hello_marshal(_env);

      // Message send
      _env.send();

      // Message receive
      _env.receive();

      // Calling the unmarshal function
      return _hello_unmarshal(_env);
    }

    // Marshal operation for "hello"
    public static void _hello_marshal(com.ericsson.otp.ic.Environment __env)
      throws java.lang.Exception {

      com.ericsson.otp.erlang.OtpOutputStream __os = __env.getOs();

      // Message header assembly
      __os.reset();
      __os.write_tuple_head(3);
      __os.write_atom("$gen_call");

      // Message identity part creation
      __os.write_tuple_head(2);
      __env.write_client_pid();
      __env.write_client_ref();

      __os.write_atom("hello");
    }

    // Unmarshal operation for "hello"
    public static java.lang.String _hello_unmarshal(com.ericsson.otp.ic.Environment __env)
      throws java.lang.Exception {

      // Get input stream
      com.ericsson.otp.erlang.OtpInputStream __is = __env.getIs();

      // Extracting return value
      return __is.read_string();
    }


    // Operation "DbWork::addNode" implementation
    public java.lang.String addNode(java.lang.String name)
      throws java.lang.Exception {

      // Calling the marshal function
      _addNode_marshal(_env, name);

      // Message send
      _env.send();

      // Message receive
      _env.receive();

      // Calling the unmarshal function
      return _addNode_unmarshal(_env);
    }

    // Marshal operation for "addNode"
    public static void _addNode_marshal(com.ericsson.otp.ic.Environment __env, java.lang.String name)
      throws java.lang.Exception {

      com.ericsson.otp.erlang.OtpOutputStream __os = __env.getOs();

      // Message header assembly
      __os.reset();
      __os.write_tuple_head(3);
      __os.write_atom("$gen_call");

      // Message identity part creation
      __os.write_tuple_head(2);
      __env.write_client_pid();
      __env.write_client_ref();

      // Operation attribute creation
      __os.write_tuple_head(2);
      __os.write_atom("addNode");
      __os.write_string(name);
    }

    // Unmarshal operation for "addNode"
    public static java.lang.String _addNode_unmarshal(com.ericsson.otp.ic.Environment __env)
      throws java.lang.Exception {

      // Get input stream
      com.ericsson.otp.erlang.OtpInputStream __is = __env.getIs();

      // Extracting return value
      return __is.read_string();
    }


    // Operation "DbWork::getNode" implementation
    public java.lang.String getNode(java.lang.String name)
      throws java.lang.Exception {

      // Calling the marshal function
      _getNode_marshal(_env, name);

      // Message send
      _env.send();

      // Message receive
      _env.receive();

      // Calling the unmarshal function
      return _getNode_unmarshal(_env);
    }

    // Marshal operation for "getNode"
    public static void _getNode_marshal(com.ericsson.otp.ic.Environment __env, java.lang.String name)
      throws java.lang.Exception {

      com.ericsson.otp.erlang.OtpOutputStream __os = __env.getOs();

      // Message header assembly
      __os.reset();
      __os.write_tuple_head(3);
      __os.write_atom("$gen_call");

      // Message identity part creation
      __os.write_tuple_head(2);
      __env.write_client_pid();
      __env.write_client_ref();

      // Operation attribute creation
      __os.write_tuple_head(2);
      __os.write_atom("getNode");
      __os.write_string(name);
    }

    // Unmarshal operation for "getNode"
    public static java.lang.String _getNode_unmarshal(com.ericsson.otp.ic.Environment __env)
      throws java.lang.Exception {

      // Get input stream
      com.ericsson.otp.erlang.OtpInputStream __is = __env.getIs();

      // Extracting return value
      return __is.read_string();
    }


    // Operation "DbWork::addRelationship" implementation
    public java.lang.String addRelationship(java.lang.String node1, java.lang.String node2)
      throws java.lang.Exception {

      // Calling the marshal function
      _addRelationship_marshal(_env, node1, node2);

      // Message send
      _env.send();

      // Message receive
      _env.receive();

      // Calling the unmarshal function
      return _addRelationship_unmarshal(_env);
    }

    // Marshal operation for "addRelationship"
    public static void _addRelationship_marshal(com.ericsson.otp.ic.Environment __env, java.lang.String node1, java.lang.String node2)
      throws java.lang.Exception {

      com.ericsson.otp.erlang.OtpOutputStream __os = __env.getOs();

      // Message header assembly
      __os.reset();
      __os.write_tuple_head(3);
      __os.write_atom("$gen_call");

      // Message identity part creation
      __os.write_tuple_head(2);
      __env.write_client_pid();
      __env.write_client_ref();

      // Operation attribute creation
      __os.write_tuple_head(3);
      __os.write_atom("addRelationship");
      __os.write_string(node1);
      __os.write_string(node2);
    }

    // Unmarshal operation for "addRelationship"
    public static java.lang.String _addRelationship_unmarshal(com.ericsson.otp.ic.Environment __env)
      throws java.lang.Exception {

      // Get input stream
      com.ericsson.otp.erlang.OtpInputStream __is = __env.getIs();

      // Extracting return value
      return __is.read_string();
    }


    // Operation "DbWork::getRelationship" implementation
    public java.lang.String getRelationship(java.lang.String node1, java.lang.String node2)
      throws java.lang.Exception {

      // Calling the marshal function
      _getRelationship_marshal(_env, node1, node2);

      // Message send
      _env.send();

      // Message receive
      _env.receive();

      // Calling the unmarshal function
      return _getRelationship_unmarshal(_env);
    }

    // Marshal operation for "getRelationship"
    public static void _getRelationship_marshal(com.ericsson.otp.ic.Environment __env, java.lang.String node1, java.lang.String node2)
      throws java.lang.Exception {

      com.ericsson.otp.erlang.OtpOutputStream __os = __env.getOs();

      // Message header assembly
      __os.reset();
      __os.write_tuple_head(3);
      __os.write_atom("$gen_call");

      // Message identity part creation
      __os.write_tuple_head(2);
      __env.write_client_pid();
      __env.write_client_ref();

      // Operation attribute creation
      __os.write_tuple_head(3);
      __os.write_atom("getRelationship");
      __os.write_string(node1);
      __os.write_string(node2);
    }

    // Unmarshal operation for "getRelationship"
    public static java.lang.String _getRelationship_unmarshal(com.ericsson.otp.ic.Environment __env)
      throws java.lang.Exception {

      // Get input stream
      com.ericsson.otp.erlang.OtpInputStream __is = __env.getIs();

      // Extracting return value
      return __is.read_string();
    }


}

