package server_side;

//------------------------------------------------------------
//
// Implementation stub file
// 
// Target: DbWork
// Source: d:/programming/temp/erl/java/dbwork.idl
// IC vsn: 4.3
// 
// This file is automatically generated. DO NOT EDIT IT.
//
//------------------------------------------------------------


public interface DbWork {

/*
 * Operation "DbWork::hello" interface functions 
 */

java.lang.String hello()
     throws java.lang.Exception;


/*
 * Operation "DbWork::addNode" interface functions 
 */

java.lang.String addNode(java.lang.String name)
     throws java.lang.Exception;


/*
 * Operation "DbWork::getNode" interface functions 
 */

java.lang.String getNode(java.lang.String name)
     throws java.lang.Exception;


/*
 * Operation "DbWork::addRelationship" interface functions 
 */

java.lang.String addRelationship(java.lang.String node1, java.lang.String node2)
     throws java.lang.Exception;


/*
 * Operation "DbWork::getRelationship" interface functions 
 */

java.lang.String getRelationship(java.lang.String node1, java.lang.String node2)
     throws java.lang.Exception;


}

