package server_side;

//------------------------------------------------------------
//
// Implementation stub file
// 
// Target: DbWorkHelper
// Source: d:/programming/temp/erl/java/dbwork.idl
// IC vsn: 4.3
// 
// This file is automatically generated. DO NOT EDIT IT.
//
//------------------------------------------------------------


public final class DbWorkHelper {

    // Constructor
    public DbWorkHelper() {
    }

    public static void _marshal() {
        // Writing the object to the message
    }

    public static DbWork _unmarshal() {
        // Reading the object from the message
        return null;
    }

    public static java.lang.String id() {
        return "IDL:DbWork:1.0";
    }

}

