package server_side;

//------------------------------------------------------------
//
// Implementation stub file
// 
// Target: DbWorkHolder
// Source: d:/programming/temp/erl/java/dbwork.idl
// IC vsn: 4.3
// 
// This file is automatically generated. DO NOT EDIT IT.
//
//------------------------------------------------------------


public final class DbWorkHolder {

    // Instance variable
    public DbWork value;

    // Constructors
    public DbWorkHolder() {
        this(null);
    }

    public DbWorkHolder(DbWork _arg) {
        value = _arg;
    }

    public void _marshal() {
    }

    public void _unmarshal() {
    }

}

